# Basic workflow

name: CI

# Triggers
on:
  # Triggers workflow when push/pull request happens on main branch
  push:
    branches: ["main"]
    # Default branch can be mentioned in the branches on which the workflow has to be triggered.
  pull_request:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: string
        required: true
      
# Jobs - a workflow run is made up of one/more jobs that can run parallel or sequentially.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run multi-line script
        run: |
          echo "line 1"
          echo "line 2"
